### ISSUE TITLE
Rmd correction

### ISSUE THREAD

**Issue by kyleGrealis** [Chhr1s/Distill_Website#3]
There's an issue with the numeric value assigned to the years in the .Rmd file. 2015-2017 is described as years 1-3 in the text, but are 0-2 in the dataset

**Comment by Chhr1s** [comment]
Oops, thanks for pointing that out—good catch! Somehow I missed this notification last year. This article was written pretty hastily as a feasibility for something else and, truth be told, I probably won't go in and fix it until I do a website revamp. I haven't updated in a long time.

Since you're looking at this you'll probably get value from my `gmerf_ranger` repo here where I use ranger() for the random forest back-end. It's much faster than longituRF implementation. I might get around to putting that into a package sometime, but it won't be soon. Right now it's a fitting and prediction function you'd have to tweak yourself.
